name: 'Publish to NPM'
description: Github action to publish to NPM

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'
    - shell: bash
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        yarn install
        git add . && git commit -m "fix: install dependencies"
        yarn release-it --npm.publishArgs="--registry=https://registry.npmjs.org" --npm.skipChecks