name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  run-lint-pr:
    name: Lint PR title 📝
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: ./.github/actions/lint-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}