name: Workflow that will publish our module based on release-it config

on:
  workflow_dispatch:

jobs:
  release-it:
    name: Release based on release-it configuration
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: ./.github/actions/publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
