name: Pull request workflow

on:
  # workflow_dispatch:
  # pull_request:
  push:
    branches:
      - feature/interaction-test

jobs:
  commitlint:
    name: Commit lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
        with:
          configFile: ./commitlint.config.cjs
          
  # run-lint:
  #   name: Check Lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
  #     - uses: ./.github/actions/lint
  # run-unit-tests:
  #   name: Run Unit Tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
  #     - uses: ./.github/actions/unit-test
  # build:
  #   name: Build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
  #     - uses: ./.github/actions/build
  # run-interaction-test:
  #   name: Run Interaction Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
  #     - uses: ./.github/actions/interaction-test
